### ISSUE TITLE
parallel reading a lot of fasta files?

### ISSUE THREAD

**Issue by jianshu93** [natir/fastmap#2]
Hello Natir,

I have more than 1 million fasta files to parse, each is about 3-5 Mb, total is about 3T, I am wondering how I can read those huge number of files in parallel using all cpu cores I have. It seems there are not such tool available right now. Any suggestions?

Thanks,

Jianshu

**Comment by natir** [comment]
You are in the best case, a good solution could be use rayon to run your analysis on each file in parallel.

But if your analysis is short you didn't get any speed advantage with multi-threading because you are limited by your disc reading performance.

If you need a large data structure to store your result you probably going use a Mutex and Async pointer, and this reduce your gain of speed due to concurrent data access. But if your result are small you can use parallel algorithm merging available in rayon.

Other tips:
- Use BufReader with reading buffer larger than your file so reader make on call systeme and all file is now in ram
- You can try use different parser to found the one faster for your usage
- Think to profile your app to determinate which part of your analysis take more time and try to improve it. Use cargo flamegraph.
- If you use hash function didn't use default rust HashMap hash algorithm isn't the speedest, use rustc_hash or fxhash.

**Comment by jianshu93** [comment]
Hello Natir,

Thanks for the response. Yes, the fasta file analysis is very fast via minhash and it is paralleled. Now the limiting step is parsing actually. I do hash for every 10,000 files using all my threads while parsing is sequential, which is 5 times slower compared to the hash step.  I will try to using rayon to split the work among all my threads. I think there will be a huge gain.


Thanks,

Jianshu
